# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: true
language: python
virtualenv:
  system_site_packages: false
matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py36" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
before_install:
  - apt install -y libopenvdb-dev build-essential

install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - python setup.py develop
  - tox
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
